CREATE TABLE IF NOT EXISTS senda_assisted_referrals (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    senda_attention_id INT UNSIGNED NOT NULL,
    senda_person_id INT UNSIGNED NOT NULL,
    request_date DATE NOT NULL,
    request_type VARCHAR(80) NULL,
    requesting_device VARCHAR(180) NULL,
    requesting_commune VARCHAR(120) NULL,
    destination_center VARCHAR(180) NULL,
    destination_commune VARCHAR(120) NULL,
    applicant_name VARCHAR(180) NOT NULL,
    applicant_role VARCHAR(120) NULL,
    applicant_institution VARCHAR(180) NULL,
    applicant_phone VARCHAR(30) NULL,
    applicant_email VARCHAR(150) NULL,
    applicant_relationship VARCHAR(80) NULL,
    gender VARCHAR(40) NULL,
    health_insurance VARCHAR(80) NULL,
    nationality VARCHAR(80) NULL,
    indigenous_people VARCHAR(80) NULL,
    emergency_contact_name VARCHAR(180) NULL,
    emergency_contact_phone VARCHAR(30) NULL,
    substances TEXT NULL,
    age_of_onset VARCHAR(40) NULL,
    consumption_frequency VARCHAR(80) NULL,
    consumption_route VARCHAR(80) NULL,
    mental_health_history TEXT NULL,
    physical_health_history TEXT NULL,
    family_situation TEXT NULL,
    legal_situation TEXT NULL,
    support_network TEXT NULL,
    has_previous_treatments TINYINT(1) NOT NULL DEFAULT 0,
    previous_treatments_detail TEXT NULL,
    suicide_risk VARCHAR(40) NULL,
    violence_risk VARCHAR(40) NULL,
    street_situation TINYINT(1) NULL,
    pregnancy TINYINT(1) NULL,
    children_in_care TINYINT(1) NULL,
    overall_risk VARCHAR(40) NULL,
    risk_notes TEXT NULL,
    assist_applicable TINYINT(1) NOT NULL DEFAULT 0,
    assist_data JSON NULL,
    observations TEXT NULL,
    is_completed TINYINT(1) NOT NULL DEFAULT 0,
    created_by INT UNSIGNED NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    INDEX idx_senda_assisted_referrals_attention (senda_attention_id),
    INDEX idx_senda_assisted_referrals_person (senda_person_id),
    INDEX idx_senda_assisted_referrals_deleted_at (deleted_at),
    CONSTRAINT fk_senda_assisted_referrals_attention FOREIGN KEY (senda_attention_id) REFERENCES senda_attentions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_senda_assisted_referrals_person FOREIGN KEY (senda_person_id) REFERENCES senda_people(id) ON DELETE RESTRICT,
    CONSTRAINT fk_senda_assisted_referrals_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS senda_referrals;
