CREATE TABLE IF NOT EXISTS women_people (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    first_names VARCHAR(150) NOT NULL,
    paternal_surname VARCHAR(120) NOT NULL,
    maternal_surname VARCHAR(120) NULL,
    rut VARCHAR(20) NOT NULL,
    rut_normalized VARCHAR(12) NOT NULL,
    birth_date DATE NOT NULL,
    phone VARCHAR(30) NULL,
    email VARCHAR(150) NULL,
    address VARCHAR(255) NULL,
    sector_id INT UNSIGNED NULL,
    nationality VARCHAR(80) NULL,
    occupation VARCHAR(150) NULL,
    education_level_id INT UNSIGNED NULL,
    safe_contact VARCHAR(20) NULL,
    safe_contact_notes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY uq_women_people_rut_normalized (rut_normalized),
    INDEX idx_women_people_deleted_at (deleted_at),
    INDEX idx_women_people_name (paternal_surname, maternal_surname, first_names),
    INDEX idx_women_people_sector (sector_id),
    CONSTRAINT fk_women_people_sector FOREIGN KEY (sector_id) REFERENCES sectors(id),
    CONSTRAINT fk_women_people_education FOREIGN KEY (education_level_id) REFERENCES women_education_levels(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
