CREATE TABLE IF NOT EXISTS women_cases (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    case_number VARCHAR(30) NOT NULL,
    reported_at DATETIME NOT NULL,
    report_channel_id INT UNSIGNED NULL,
    report_channel_other VARCHAR(180) NULL,
    incident_date_precision VARCHAR(20) NOT NULL DEFAULT 'undetermined',
    incident_date DATE NULL,
    incident_time TIME NULL,
    incident_time_notes VARCHAR(120) NULL,
    incident_place VARCHAR(180) NULL,
    incident_sector_id INT UNSIGNED NULL,
    incident_address VARCHAR(255) NULL,
    description TEXT NULL,
    affected_person_id INT UNSIGNED NOT NULL,
    relationship_type_id INT UNSIGNED NULL,
    relationship_other VARCHAR(180) NULL,
    current_relationship VARCHAR(20) NULL,
    is_first_occurrence VARCHAR(20) NULL,
    occurrence_frequency VARCHAR(120) NULL,
    occurring_since VARCHAR(120) NULL,
    occurrence_notes TEXT NULL,
    has_previous_reports VARCHAR(20) NULL,
    has_formal_current_report VARCHAR(20) NULL,
    has_linked_minors VARCHAR(20) NULL,
    has_dependents VARCHAR(20) NULL,
    dependents_count TINYINT UNSIGNED NULL,
    dependents_notes TEXT NULL,
    has_protective_measures VARCHAR(20) NULL,
    priority VARCHAR(20) NULL,
    priority_assigned_by INT UNSIGNED NULL,
    priority_assigned_at DATETIME NULL,
    case_status_id INT UNSIGNED NOT NULL,
    closed_at DATETIME NULL,
    closed_by INT UNSIGNED NULL,
    closure_notes TEXT NULL,
    cancelled_at DATETIME NULL,
    cancelled_by INT UNSIGNED NULL,
    cancellation_reason TEXT NULL,
    created_by INT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY uq_women_cases_case_number (case_number),
    INDEX idx_women_cases_reported_at (reported_at),
    INDEX idx_women_cases_status (case_status_id),
    INDEX idx_women_cases_priority (priority),
    INDEX idx_women_cases_affected_person (affected_person_id),
    INDEX idx_women_cases_incident_sector (incident_sector_id),
    INDEX idx_women_cases_created_by (created_by),
    INDEX idx_women_cases_deleted_at (deleted_at),
    CONSTRAINT fk_women_cases_report_channel FOREIGN KEY (report_channel_id) REFERENCES women_report_channels(id),
    CONSTRAINT fk_women_cases_relationship FOREIGN KEY (relationship_type_id) REFERENCES women_relationship_types(id),
    CONSTRAINT fk_women_cases_affected_person FOREIGN KEY (affected_person_id) REFERENCES women_people(id),
    CONSTRAINT fk_women_cases_incident_sector FOREIGN KEY (incident_sector_id) REFERENCES sectors(id),
    CONSTRAINT fk_women_cases_status FOREIGN KEY (case_status_id) REFERENCES women_case_statuses(id),
    CONSTRAINT fk_women_cases_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_women_cases_priority_by FOREIGN KEY (priority_assigned_by) REFERENCES users(id),
    CONSTRAINT fk_women_cases_closed_by FOREIGN KEY (closed_by) REFERENCES users(id),
    CONSTRAINT fk_women_cases_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
