CREATE TABLE IF NOT EXISTS meetings (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    meeting_number VARCHAR(32) NOT NULL,
    source_module VARCHAR(40) NOT NULL,
    source_record_id INT UNSIGNED NULL,
    meeting_date DATE NOT NULL,
    meeting_time TIME NOT NULL,
    meeting_place VARCHAR(255) NOT NULL,
    additional_notes TEXT NULL,
    next_meeting_required TINYINT(1) NOT NULL DEFAULT 0,
    next_meeting_date DATE NULL,
    next_meeting_time TIME NULL,
    next_meeting_notes TEXT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'draft',
    content_hash CHAR(64) NULL,
    content_version INT UNSIGNED NOT NULL DEFAULT 1,
    created_by INT UNSIGNED NOT NULL,
    finalized_at DATETIME NULL,
    completed_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    cancelled_by INT UNSIGNED NULL,
    cancellation_reason TEXT NULL,
    reopened_at DATETIME NULL,
    reopened_by INT UNSIGNED NULL,
    reopen_reason TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    UNIQUE KEY uk_meetings_number (meeting_number),
    KEY idx_meetings_source (source_module, source_record_id),
    KEY idx_meetings_status (status),
    KEY idx_meetings_date (meeting_date),
    KEY idx_meetings_created_by (created_by),
    KEY idx_meetings_next_date (next_meeting_date),
    CONSTRAINT fk_meetings_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_meetings_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users (id),
    CONSTRAINT fk_meetings_reopened_by FOREIGN KEY (reopened_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meeting_participants (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    meeting_id INT UNSIGNED NOT NULL,
    participant_type ENUM('internal', 'external') NOT NULL,
    user_id INT UNSIGNED NULL,
    external_name VARCHAR(200) NULL,
    external_position VARCHAR(150) NULL,
    external_organization VARCHAR(150) NULL,
    external_email VARCHAR(150) NULL,
    signature_required TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_meeting_participants_meeting (meeting_id),
    KEY idx_meeting_participants_user (user_id),
    CONSTRAINT fk_meeting_participants_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    CONSTRAINT fk_meeting_participants_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meeting_topics (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    meeting_id INT UNSIGNED NOT NULL,
    position INT UNSIGNED NOT NULL DEFAULT 1,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_meeting_topics_meeting (meeting_id),
    CONSTRAINT fk_meeting_topics_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meeting_agreements (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    meeting_id INT UNSIGNED NOT NULL,
    position INT UNSIGNED NOT NULL DEFAULT 1,
    description TEXT NOT NULL,
    responsible_user_id INT UNSIGNED NULL,
    responsible_text VARCHAR(200) NULL,
    due_date DATE NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_meeting_agreements_meeting (meeting_id),
    KEY idx_meeting_agreements_responsible (responsible_user_id),
    CONSTRAINT fk_meeting_agreements_meeting FOREIGN KEY (meeting_id) REFERENCES meetings (id) ON DELETE CASCADE,
    CONSTRAINT fk_meeting_agreements_responsible FOREIGN KEY (responsible_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
