<?php

declare(strict_types=1);

/**
 * Mapa de permisos por rol de sistema.
 * '*' otorga todos los permisos del catálogo.
 */
return [
    'superadministrador' => ['*'],

    'administrador_seguridad' => [
        'dashboard.access',
        'users.access', 'users.view', 'users.create', 'users.update', 'users.delete',
        'roles.access', 'roles.view', 'roles.create', 'roles.update',
        'permissions.view',
        'audit.access', 'audit.view',
        'settings.access',
        'sectors.access', 'sectors.view', 'sectors.create', 'sectors.update', 'sectors.delete',
        'security.access',
        'senda.access',
        'senda.dashboard.view',
        'senda.people.view',
        'senda.attentions.view',
        'senda.referrals.view',
        'senda.followups.view',
        'senda.statistics.view',
        'cctv.access',
        'cctv.dashboard.view',
        'cctv.shifts.view', 'cctv.shifts.create', 'cctv.shifts.close', 'cctv.shifts.view_all', 'cctv.shifts.edit_closed',
        'cctv.log.view', 'cctv.log.create', 'cctv.log.edit', 'cctv.log.delete', 'cctv.log.view_all', 'cctv.log.edit_closed',
        'cctv.cameras.view', 'cctv.cameras.manage',
        'cctv.visits.view', 'cctv.visits.create', 'cctv.visits.edit',
        'cctv.recordings.view', 'cctv.recordings.create', 'cctv.recordings.edit',
        'cctv.recordings.review', 'cctv.recordings.approve', 'cctv.recordings.deliver',
        'cctv.recordings.view_complaint_document', 'cctv.recordings.verify_complaint',
        'cctv.recordings.assign', 'cctv.recordings.export', 'cctv.recordings.edit_delivered',
        'cctv.recordings.cancel',
        'cctv.reports.view', 'cctv.reports.export',
        'women.access', 'women.dashboard.view', 'women.cases.view', 'women.cases.view_all', 'women.audit.view',
        'meetings.access', 'meetings.view', 'meetings.view_all', 'meetings.sign', 'meetings.view_pending_signatures', 'meetings.reopen', 'meetings.cancel',
        'guards.access', 'guards.shifts.view', 'guards.shifts.create', 'guards.shifts.update',
    ],

    'operador_camaras' => [
        'dashboard.access',
        'cctv.access',
        'cctv.dashboard.view',
        'cctv.shifts.view',
        'cctv.shifts.create',
        'cctv.shifts.close',
        'cctv.log.view',
        'cctv.log.create',
        'cctv.log.edit',
        'cctv.cameras.view',
        'cctv.visits.view',
        'cctv.visits.create',
        'cctv.recordings.view',
        'cctv.recordings.create',
    ],

    'senda' => [
        'dashboard.access',
        'senda.access',
        'senda.dashboard.view',
        'senda.people.view', 'senda.people.create', 'senda.people.edit',
        'senda.attentions.view', 'senda.attentions.create', 'senda.attentions.edit',
        'senda.referrals.view', 'senda.referrals.create', 'senda.referrals.edit',
        'senda.followups.view', 'senda.followups.create', 'senda.followups.edit', 'senda.followups.delete',
        'senda.statistics.view',
        'senda.meetings.view', 'senda.meetings.create',
        'meetings.access', 'meetings.view', 'meetings.create', 'meetings.edit', 'meetings.sign', 'meetings.view_pending_signatures', 'meetings.signature.manage', 'meetings.reopen',
    ],

    'oficina_mujer' => [
        'dashboard.access',
        'women.access',
        'women.dashboard.view',
        'women.cases.view',
        'women.cases.view_all',
        'women.cases.create',
        'women.cases.edit',
        'women.cases.edit_closed',
        'women.cases.close',
        'women.people.view',
        'women.people.create',
        'women.people.edit',
        'women.followups.view',
        'women.followups.create',
        'women.followups.edit',
        'women.statistics.view',
        'women.audit.view',
        'women.documents.view',
        'women.documents.upload',
    ],

    'guardias' => [
        'dashboard.access',
        'guards.access',
        'guards.shifts.view',
        'guards.shifts.create',
        'guards.shifts.update',
    ],

    'consulta' => [
        'dashboard.access',
        'security.access',
        'senda.access',
        'senda.dashboard.view',
        'senda.people.view',
        'senda.attentions.view',
        'senda.referrals.view',
        'senda.followups.view',
        'senda.statistics.view',
        'cctv.access',
        'cctv.dashboard.view',
        'cctv.shifts.view',
        'cctv.shifts.view_all',
        'cctv.log.view',
        'cctv.log.view_all',
        'cctv.cameras.view',
        'cctv.visits.view',
        'cctv.recordings.view',
        'cctv.reports.view',
        'women.access', 'women.dashboard.view', 'women.cases.view',
        'guards.access', 'guards.shifts.view',
    ],
];
